version: '3.7'

services:
  odataapi:
    image: odataapi
    build:
      context: .
      dockerfile: ODataAPI/Dockerfile
  
  postgres:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4


volumes:
  postgres-data:
  pgadmin_data: